// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workshop.Api.Data;

#nullable disable

namespace Workshop.Api.Migrations
{
    [DbContext(typeof(WorkshopDbContext))]
    [Migration("20251017152743_AddFloorPlanPositions")]
    partial class AddFloorPlanPositions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Workshop.Api.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street, Downtown",
                            IsActive = true,
                            Name = "Downtown Location"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 North Avenue",
                            IsActive = true,
                            Name = "North Branch"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 East Boulevard",
                            IsActive = true,
                            Name = "East Side Location"
                        });
                });

            modelBuilder.Entity("Workshop.Api.Data.Entities.ReservableObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("ReservableObjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk 101",
                            PositionX = 2,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = false,
                            LocationId = 1,
                            Name = "Desk 201",
                            PositionX = 5,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk 301",
                            PositionX = 8,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = false,
                            LocationId = 1,
                            Name = "Desk 401",
                            PositionX = 2,
                            PositionY = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Desk 501",
                            PositionX = 5,
                            PositionY = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Parking A-1",
                            PositionX = 2,
                            PositionY = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = false,
                            LocationId = 1,
                            Name = "Parking A-2",
                            PositionX = 5,
                            PositionY = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = true,
                            LocationId = 1,
                            Name = "Parking A-3",
                            PositionX = 8,
                            PositionY = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = false,
                            LocationId = 2,
                            Name = "Desk 102",
                            PositionX = 2,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Desk 202",
                            PositionX = 5,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            IsAvailable = false,
                            LocationId = 2,
                            Name = "Desk 302",
                            PositionX = 8,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Desk 402",
                            PositionX = 2,
                            PositionY = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Desk 502",
                            PositionX = 5,
                            PositionY = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            IsAvailable = false,
                            LocationId = 2,
                            Name = "Parking B-1",
                            PositionX = 2,
                            PositionY = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Parking B-2",
                            PositionX = 5,
                            PositionY = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            IsAvailable = true,
                            LocationId = 2,
                            Name = "Parking B-3",
                            PositionX = 8,
                            PositionY = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk 103",
                            PositionX = 2,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk 203",
                            PositionX = 5,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk 303",
                            PositionX = 8,
                            PositionY = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Desk 403",
                            PositionX = 2,
                            PositionY = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            IsAvailable = false,
                            LocationId = 3,
                            Name = "Desk 503",
                            PositionX = 5,
                            PositionY = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Parking C-1",
                            PositionX = 2,
                            PositionY = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Parking C-2",
                            PositionX = 5,
                            PositionY = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            IsAvailable = true,
                            LocationId = 3,
                            Name = "Parking C-3",
                            PositionX = 8,
                            PositionY = 8,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Workshop.Api.Data.Entities.ReservableObject", b =>
                {
                    b.HasOne("Workshop.Api.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
